src/Fase.Web/Models/Blocks/ArtistsBlock.cs
using System.ComponentModel.DataAnnotations;
using Piranha.AttributeBuilder;
using Piranha.Extend;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Artists block", Category = "Content", Icon = "fas fa-music")]
    public class ArtistsBlock : TextAndImageBlock
    {
        public ArtistsBlock()
        {
            ArtistsPage = new PageField();
        }

        [Field]
        [Display(Name = "Artists page")]
        public PageField ArtistsPage { get; set; }
    }
}

src/Fase.Web/Models/Blocks/ContactBlock.cs
using Piranha.AttributeBuilder;
using Piranha.Extend;
using Piranha.Extend.Fields;
using Block = Piranha.Extend.Block;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Contact block", Category = "Content", Icon = "fas fa-address-book")]
    public class ContactBlock : Block
    {
        public ContactBlock()
        {
            ContactPage = new PageField();
        }

        [Field(Title = "Contact page")]
        public PageField ContactPage { get; set; }
    }
}

src/Fase.Web/Models/Blocks/EventScheduleBlock.cs
using Piranha.Extend;
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Schedule block", Category = "Content", Icon = "fas fa-clock")]
    public class EventScheduleBlock : Block
    {
        public EventScheduleBlock()
        {
            SchedulePage = new PageField();
        }

        [Field(Title = "Schedule page")]
        public PageField SchedulePage { get; set; }
    }
}

src/Fase.Web/Models/Blocks/PartnersBlock.cs
using Piranha.Extend;
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Partners block", Category = "Content", Icon = "fas fa-handshake")]
    public class PartnersBlock : Block
    {
        public PartnersBlock()
        {
            PartnersPage = new PageField();
        }

        [Field]
        public PageField PartnersPage { get; set; }
    }
}

src/Fase.Web/Models/Blocks/SignupBlock.cs
using System.ComponentModel.DataAnnotations;
using Piranha.AttributeBuilder;
using Piranha.Extend;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Signup block", Category = "Content", Icon = "fas fa-user-plus")]
    public class SignupBlock : Block
    {
        [Field]
        public StringField Heading { get; set; }

        [Field]
        [Display(Name = "Email subject")]
        public StringField EmailSubject { get; set; }
    }
}

src/Fase.Web/Models/Blocks/TeaserBlock.cs
using Piranha.AttributeBuilder;
using Piranha.Extend;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Teaser block", Category = "Content", Icon = "fas fa-newspaper")]
    public class TeaserBlock : Block
    {
        [Field]
        public ImageField Image { get; set; }

        [Field]
        public StringField Heading { get; set; }

        [Field]
        public HtmlField Text { get; set; }
    }
}

src/Fase.Web/Models/Blocks/TextAndImageBlock.cs
using Piranha.AttributeBuilder;
using Piranha.Extend;
using Piranha.Extend.Fields;
using System.ComponentModel.DataAnnotations;

namespace Fase.Web.Models.Blocks
{
    [BlockType(Name = "Text block with image", Category = "Content", Icon = "fas fa-newspaper")]
    public class TextAndImageBlock : Block
    {
        [Field]
        public StringField Heading { get; set; }

        [Field(Title = "Sub heading")]
        [Display(Name = "Sub heading")]
        public StringField SubHeading { get; set; }

        [Field]
        public HtmlField Text { get; set; }

        [Field]
        public ImageField Image { get; set; }

        [Field(Title = "Block style")]
        [Display(Name = "Block style")]
        public SelectField<TextBlockCssClass> CssClass { get; set; }

        public string GetCssClass()
        {
            switch (CssClass?.Value)
            {
                case TextBlockCssClass.Grey:
                    return "text-block text-block--grey";
                default:
                    return "text-block";
            }
        }
    }
}

src/Fase.Web/Models/EventPage.cs
using System;
using Fase.Web.Models.Regions;
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Models;

namespace Fase.Web.Models
{
    [PageType(Title = "Event page")]
    [PageTypeRoute(Title = "Event", Route = "/event")]
    public class EventPage : Page<EventPage>
    {
        public EventPage()
        {
            Hero = new Hero
            {
                CssClass = new SelectField<HeroCssClass>
                {
                    Value = HeroCssClass.Content,
                }
            };

            Details = new EventDetails();
        }

        [Region]
        public Hero Hero { get; set; }

        [Region(Title = "Event details")]
        public EventDetails Details { get; set; }

        public DateTime? StartDate => Details.StartDate.Value;

        public DateTime? EndDate => Details.EndDate.Value ?? Details.StartDate.Value;
    }
}

src/Fase.Web/Models/EventSchedulePage.cs
using System.Collections.Generic;
using Fase.Web.Models.Regions;
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;
using Piranha.Models;

namespace Fase.Web.Models
{
    [PageType(Title = "Event schedule page")]
    [PageTypeRoute(Title = "Event schedule", Route = "/eventschedule")]
    public class EventSchedulePage : Page<EventSchedulePage>
    {
        public EventSchedulePage()
        {
            Hero = new Hero
            {
                CssClass = new SelectField<HeroCssClass>
                {
                    Value = HeroCssClass.Content
                }
            };

            Items = new List<ScheduleItem>();
        }

        [Region(Title = "Hero")]
        public Hero Hero { get; set; }

        [Region(Title = "Schedule", ListTitle = "Heading")]
        public IList<ScheduleItem> Items { get; set; }
    }
}

src/Fase.Web/Models/Regions/ArticleImage.cs
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Regions
{
    public class ArticleImage
    {
        [Field]
        public ImageField MainImage { get; set; }

        public bool ShouldRender()
        {
            return false;
        }
    }
}

src/Fase.Web/Models/Regions/Hero.cs
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Regions
{
    public class Hero
    {
        [Field(Title = "Background image")]
        public ImageField BackgroundImage { get; set; }

        [Field]
        public ImageField Logo { get; set; }

        [Field]
        public TextField Heading { get; set; }

        [Field]
        public HtmlField Text { get; set; }

        [Field]
        public SelectField<HeroCssClass> CssClass { get; set; }

        public bool ShouldRender()
        {
            return BackgroundImage.HasValue
                || Logo.HasValue
                || !string.IsNullOrEmpty(Heading?.Value)
                || !string.IsNullOrEmpty(Text?.Value);
        }

        public string GetCssClass()
        {
            switch (CssClass?.Value)
            {
                case HeroCssClass.Medium:
                    return "hero hero--medium";
                case HeroCssClass.Content:
                    return "hero hero--static";
                case HeroCssClass.Video:
                    return "hero hero--video";
                default:
                    return "hero hero--small";
            }
        }
    }
}

src/Fase.Web/Models/Regions/Partner.cs
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Regions
{
    public class Partner
    {
        [Field]
        public StringField Name { get; set; }

        [Field]
        public ImageField Logo { get; set; }

        [Field(Title = "Website")]
        public StringField WebsiteUrl { get; set; }
    }
}

src/Fase.Web/Models/Regions/ScheduleItem.cs
using Piranha.AttributeBuilder;
using Piranha.Extend.Fields;

namespace Fase.Web.Models.Regions
{
    public class ScheduleItem
    {
        [Field(Title = "Image")]
        public ImageField ListingImage { get; set; }

        [Field]
        public StringField Heading { get; set; }

        [Field]
        public StringField Time { get; set; }

        [Field]
        public StringField Location { get; set; }

        [Field]
        public TextField Intro { get; set; }

        [Field]
        public HtmlField Description { get; set; }
    }
}

src/Fase.Web/Controllers/CmsController.cs
using Microsoft.AspNetCore.Mvc;
using Piranha;
using System;
using System.Linq;
using System.Threading.Tasks;
using Fase.Web.Models;
using Fase.Web.Models.ViewModels;
using Fase.Web.Repositories;
using Piranha.Services;

namespace Fase.Web.Controllers
{
    public class CmsController : Controller
    {
        private readonly IApi _api;
        private readonly IExtendedPageRepository _extendedPageRepository;

        /// <summary>
        /// Default constructor.
        /// </summary>
        /// <param name="api">The current api</param>
        /// <param name="extendedPageRepository"></param>
        public CmsController(IApi api, IExtendedPageRepository extendedPageRepository)
        {
            _api = api;
            _extendedPageRepository = extendedPageRepository;
        }

        /// <summary>
        /// Gets the page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("page")]
        public IActionResult Page(Guid id) {
            var model = _api.Pages.GetById<StandardPage>(id);

            return View(model);
        }

        /// <summary>
        /// Gets the event listing page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("events")]
        public async Task<IActionResult> Events(Guid id)
        {
            var page = await _api.Pages.GetByIdAsync<EventListingPage>(id);
            var events = (await _extendedPageRepository.GetChildrenAsync<EventPage>(id)).ToList();
            var model = new EventsListingView(page)
            {
                UpcomingEvents = events
                    .Where(x => x.StartDate.HasValue && x.EndDate.HasValue && x.EndDate.Value > DateTime.Now)
                    .OrderBy(x => x.StartDate),
                EarlierEvents = events
                    .Where(x => x.EndDate.HasValue && x.EndDate.Value < DateTime.Now)
                    .OrderByDescending(x => x.EndDate)
            };

            return View(model);
        }

        /// <summary>
        /// Gets the event page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("event")]
        public IActionResult Event(Guid id)
        {
            var model = _api.Pages.GetById<EventPage>(id);

            return View(model);
        }

        /// <summary>
        /// Gets the partners page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("partners")]
        public IActionResult Partners(Guid id)
        {
            var model = _api.Pages.GetById<PartnersPage>(id);

            return View(model);
        }

        /// <summary>
        /// Gets the artist listing page with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("artists")]
        public IActionResult Artists(Guid id)
        {
            var model = _api.Pages.GetById<ArtistListingPage>(id);

            return View(model);
        }

        /// <summary>
        /// Gets the startpage with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("eventschedules")]
        public async Task<IActionResult> EventSchedules(Guid id)
        {
            var page = _api.Pages.GetById<EventScheduleListingPage>(id);
            var model = new EventScheduleListingView
            {
                Title = page.Title,
                Hero = page.Hero,
                Blocks = page.Blocks,
                Schedules = await _extendedPageRepository.GetChildrenAsync<EventSchedulePage>(id)
            };

            return View(model);
        }

        /// <summary>
        /// Gets the startpage with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("eventschedule")]
        public IActionResult EventSchedule(Guid id)
        {
            var model = _api.Pages.GetById<Models.EventSchedulePage>(id);

            return View(model);
        }

        /// <summary>
        /// Gets the startpage with the given id.
        /// </summary>
        /// <param name="id">The unique page id</param>
        [Route("")]
        public IActionResult Start(Guid id) {
            var model = _api.Pages.GetById<StartPage>(id);

            return View(model);
        }

        ///// <summary>
        ///// Gets the blog archive with the given id.
        ///// </summary>
        ///// <param name="id">The unique page id</param>
        ///// <param name="year">The optional year</param>
        ///// <param name="month">The optional month</param>
        ///// <param name="page">The optional page</param>
        ///// <param name="category">The optional category</param>
        ///// <param name="tag">The optional tag</param>
        //[Route("archive")]
        //public IActionResult Archive(Guid id, int? year = null, int? month = null, int? page = null, 
        //    Guid? category = null, Guid? tag = null) 
        //{
        //    Models.BlogArchive model;

        //    if (category.HasValue)
        //        model = api.Archives.GetByCategoryId<Models.BlogArchive>(id, category.Value, page, year, month);
        //    else if (tag.HasValue)
        //        model = api.Archives.GetByTagId<Models.BlogArchive>(id, tag.Value, page, year, month);
        //    else model = api.Archives.GetById<Models.BlogArchive>(id, page, year, month);

        //    return View(model);
        //}

        ///// <summary>
        ///// Gets the post with the given id.
        ///// </summary>
        ///// <param name="id">The unique post id</param>
        //[Route("post")]
        //public IActionResult Post(Guid id) {
        //    var model = api.Posts.GetById<Models.BlogPost>(id);

        //    return View(model);
        //}
    }
}

src/Fase.Web/Controllers/EmailController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Fase.Web.Models;
using Fase.Web.Models.FormModels;
using Geta.EmailNotification.AspNetCore;
using Geta.EmailNotification.Shared;
using Microsoft.AspNetCore.Mvc;

namespace Fase.Web.Controllers
{
    public class EmailController : Controller
    {
        private readonly IAsyncEmailNotificationClient _emailNotificationClient;
        private readonly IEmailNotificationRequestFactory _emailNotificationRequestFactory;

        public EmailController(IAsyncEmailNotificationClient emailNotificationClient, IEmailNotificationRequestFactory emailNotificationRequestFactory)
        {
            _emailNotificationClient = emailNotificationClient;
            _emailNotificationRequestFactory = emailNotificationRequestFactory;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Send(EmailForm model)
        {
            var response = new SendEmailResponse();

            if (!ModelState.IsValid)
            {
                response.Success = false;
                response.Data = ModelState.Keys
                    .Where(x => ModelState[x].Errors.Count > 0)
                    .Select(x => new
                    {
                        Name = x,
                        Errors = ModelState[x].Errors.Select(y => y.ErrorMessage)
                    });

                return Json(response);
            }

            try
            {
                var email = _emailNotificationRequestFactory.CreateEmailBuilder()
                    .WithFrom("mattias@geta.no")
                    .WithTo("info@fase-ab.se")
                    .WithSubject(model.Subject)
                    .WithViewName("Contact")
                    .WithViewModel(model)
                    .Build();

                var emailResponse = await _emailNotificationClient.SendAsync(email);

                response.Success = emailResponse.IsSent;
                response.Data = model;
            }
            catch (Exception exc)
            {
                response.Success = false;
                response.Message = exc.Message;
            }

            return Json(response);
        }
    }
}

src/Fase.Web/Views/Cms/DisplayTemplates/ArticleImage.cshtml
@model Fase.Web.Models.Regions.ArticleImage
@{
    if (Model == null || !Model.ShouldRender())
    {
        return;
    }
}
<div class="article__image">
    <img src="@Url.Content(Model.MainImage)" alt="">
</div>

src/Fase.Web/Views/Cms/DisplayTemplates/ArtistsBlock.cshtml
@using Fase.Web.Models
@using Piranha.Services
@model Fase.Web.Models.Blocks.ArtistsBlock
@inject Piranha.IApi Api
@{
    var artistsPage = Api.Pages.GetById<ArtistListingPage>(Model.ArtistsPage.Id.Value);
}

<article class="@Model.GetCssClass() animate" data-animate>
    <div class="animate__group">
        <h2 class="text-block__heading">
            @if (!string.IsNullOrEmpty(Model.SubHeading.Value))
            {
            <span>@Model.SubHeading</span>
            }

            @Html.Raw(Model.Heading)
        </h2>

        <div class="text-block__content text-block__body">
            @Html.Raw(Model.Text)

            @if (Model.Image.HasValue)
            {
                <p>
                    <img src="@Url.Content(Model.Image.Resize(Api, 960))" alt="">
                </p>
            }

            <ul class="profile--medium profile__list">
                @foreach (var artist in artistsPage.Artists)
                {
                    <li class="profile__item">
                        <img class="profile__image" src="@Url.Content(artist.ProfileImage)">
                        <h3 class="profile__name">@artist.Fullname</h3>
                    </li>
                }
            </ul>
        </div>
    </div>
</article>

src/Fase.Web/Views/Cms/DisplayTemplates/ContactBlock.cshtml
@using Fase.Web.Models
@using Piranha.Services
@model Fase.Web.Models.Blocks.ContactBlock
@{
    if (!Model.ContactPage.Id.HasValue)
    {
        return;
    }

    var contactPage = Api.Pages.GetById<ContactPage>(Model.ContactPage.Id.Value);

    if (contactPage == null)
    {
        return;
    }
}

<div class="animate" data-animate>
    <span id="kontakt" class="anchor"></span>
    <h2 class="text-block__heading partners-block__heading">@contactPage.Title</h2>
    <div class="text-block profile--medium">
        <ul class="profile__list">
            @foreach (var contact in contactPage.Contacts)
            {
                <li class="profile__item">
                    <img class="profile__image" src="@Url.Content(contact.ProfileImage.Resize(Api, 580, 580))">
                    <h3 class="profile__name">@($"{contact.FirstName.Value} {contact.LastName.Value}")</h3>
                    <p class="profile__text">
                        <a href="mailto:@Html.Raw(contact.Email)"><i class="icon--mail icon--lg"></i> @contact.Email</a>
                        <a href="tel:@Html.Raw(contact.Phone)"><i class="icon--phone icon--lg"></i> @Html.Raw(contact.Phone)</a>
                    </p>
                </li>
            }
        </ul>
    </div>
</div>

src/Fase.Web/Views/Cms/DisplayTemplates/EventPage.cshtml
@model Fase.Web.Models.EventPage

<li class="events__item">
    <div class="events__item__wrapper">
        <h2 class="events__item__heading">
            <i class="icon--calendar"></i>
            <a class="events__item__link" href="@Url.Content(Model.Permalink)">@Model.Title <i class="icon--right-big"></i></a>
        </h2>
        <span class="events__item__date">
            <i class="icon--clock"></i> @Html.DisplayFor(m => m.Details.StartDate) @Html.DisplayFor(m => m.Details.StartTime)
        </span>
        <div class="text-block__content text-block__body">
            @Html.Raw(Model.Details.Information)
        </div>
    </div>
</li>

src/Fase.Web/Views/Cms/DisplayTemplates/EventScheduleBlock.cshtml
@using Fase.Web.Models
@using Piranha
@using Piranha.Services
@model Fase.Web.Models.Blocks.EventScheduleBlock
@inject IApi Api
@{
    if (!Model.SchedulePage.HasValue)
    {
        return;
    }

    var schedulePage = Api.Pages.GetById<EventSchedulePage>(Model.SchedulePage.Page.Id);
}

@Html.DisplayFor(m => schedulePage)

src/Fase.Web/Views/Cms/DisplayTemplates/EventSchedulePage.cshtml
@model Fase.Web.Models.EventSchedulePage

<div class="partners-block">
    <h2 class="text-block__heading partners-block__heading">@Model.Title</h2>
    <ol class="events__list">
        @foreach (var item in Model.Items)
        {
            @Html.DisplayFor(m => item)
        }
    </ol>
</div>

src/Fase.Web/Views/Cms/DisplayTemplates/EventTime.cshtml
@using Microsoft.EntityFrameworkCore.ChangeTracking.Internal
@model Piranha.Extend.Fields.StringField

@if (!string.IsNullOrEmpty(Model.Value))
{
    <text>kl. @Model.Value</text>
}

src/Fase.Web/Views/Cms/DisplayTemplates/Hero.cshtml
@model Fase.Web.Models.Regions.Hero
@{
    if (!Model.ShouldRender())
    {
        return;
    }

    string BackgroundImage()
    {
        if (Model.BackgroundImage.HasValue)
        {
            return $"style=background-image:url({Url.Content(Model.BackgroundImage)})";
        }
        return "";
    }
}
<section class="@Model.GetCssClass()" @BackgroundImage() data-hero>
    <article class="hero__content">
        @if (Model.Logo.HasValue)
        {
            <img class="hero__logo" src="@Url.Content(Model.Logo)" alt="">
        }

        @if (!string.IsNullOrEmpty(Model.Heading))
        {
            <h1 class="hero__heading">@Model.Heading</h1>
        }

        @if (!string.IsNullOrEmpty(Model.Text))
        {
            <div class="hero__wysiwyg">
                @Html.Raw(Model.Text)
            </div>
        }
    </article>
</section>

src/Fase.Web/Views/Cms/DisplayTemplates/ImageBlock.cshtml
@model Piranha.Extend.Blocks.ImageBlock
@inject Piranha.IApi Api

<div class="image-block" style="background-image: url('@Url.Content(Model.Body.Resize(Api, 1600))')">
</div>

src/Fase.Web/Views/Cms/DisplayTemplates/ScheduleItem.cshtml
@model Fase.Web.Models.Regions.ScheduleItem

<li class="events__item">
    <div class="events__item__wrapper">
        @if (Model.ListingImage.HasValue)
        {
            <p class="events__item__intro">
                <img class="events__item__image" src="@Url.Content(Model.ListingImage.Resize(Api, 640))" alt="">
            </p>
        }
        <h2 class="events__item__heading"><i class="icon--calendar"></i> @Html.Raw(Model.Heading)</h2>
        <span class="events__item__date">
            @if (!string.IsNullOrEmpty(Model.Time?.Value))
            {
                <i class="icon--clock"></i> @Model.Time<br>
            }
            @if (!string.IsNullOrEmpty(Model.Location?.Value))
            {
                <i class="icon--location"></i> @Model.Location
            }
        </span>
        <div class="text-block__content text-block__body">
            @if (!string.IsNullOrEmpty(Model.Intro?.Value))
            {
                <p class="events__item__disclaimer">
                    @Html.Raw(Model.Intro.Value)
                </p>
            }

            @Html.Raw(Model.Description)
        </div>
    </div>
</li>

src/Fase.Web/Views/Cms/DisplayTemplates/SignupBlock.cshtml
@using Fase.Web.Extensions
@model Fase.Web.Models.Blocks.SignupBlock

<article class="text-block signup-block">
    @if (!string.IsNullOrEmpty(Model.Heading?.Value))
    {
        <h2 class="text-block__heading2">
            @Html.Raw(Model.Heading)
        </h2>
    }

    <div class="signup-block__content">
        <form asp-controller="Email" asp-action="Send" method="post" class="form text-block__body" data-form>
            <div class="form__row">
                <input class="form__input" type="text" name="Name" placeholder="Namn">
            </div>

            <div class="form__row">
                <input class="form__input" type="text" name="Company" placeholder="Bar/krog">
            </div>

            <div class="form__row">
                <input class="form__input" type="email" name="Email" placeholder="E-post">
            </div>

            <div class="form__row">
                <input class="form__input" type="text" name="Phone" placeholder="Telefon">
            </div>

            <div class="form__row">
                <button class="form__submit button button--primary" type="submit">Skicka anmälan</button>
                <p class="form__confirmation" data-form__confirmation>
                    Tack för din anmälan!
                </p>
            </div>

            <input type="hidden" name="Subject" value="@Model.EmailSubject?.Value">
        </form>
    </div>
</article>

src/Fase.Web/Views/Cms/DisplayTemplates/TeaserBlock.cshtml
@model Fase.Web.Models.Blocks.TeaserBlock
@inject Piranha.IApi Api

<div class="teaser-block animate" data-animate>
    <figure class="teaser-block__col teaser-block__image">
        @if (Model.Image.HasValue)
        {
            <img src="@Url.Content(Model.Image.Resize(Api, 960))" alt="">
        }
    </figure>
    <article class="teaser-block__col text-block__body teaser-block__body">
        <h2 class="teaser-block__heading">
            @Html.Raw(Model.Heading)
        </h2>

        @Html.Raw(Model.Text)
    </article>
</div>

src/Fase.Web/Views/Cms/DisplayTemplates/TextAndImageBlock.cshtml
@model Fase.Web.Models.Blocks.TextAndImageBlock
@inject Piranha.IApi Api

<article class="@Model.GetCssClass() animate" data-animate>
    <div class="animate__group">
        @if (!string.IsNullOrEmpty(Model.Heading?.Value))
        {
            <h2 class="text-block__heading">
                @if (!string.IsNullOrEmpty(Model.SubHeading.Value))
                {
                    <span>@Model.SubHeading</span>
                }

                @Html.Raw(Model.Heading)
            </h2>
        }

        <div class="text-block__content text-block__body">
            @Html.Raw(Model.Text)

            @if (Model.Image.HasValue)
            {
                <p>
                    <img src="@Url.Content(Model.Image.Resize(Api, 960))" alt="">
                </p>
            }
        </div>
    </div>
</article>

src/Fase.Web/Views/Cms/DisplayTemplates/TextBlock.cshtml
@model Piranha.Extend.Blocks.TextBlock

<div class="text-block">
    <div class="text-block__content text-block__body">
        <p>
            @Html.Raw(Model.Body)
        </p>
    </div>
</div>